name: Android CI

on: workflow_dispatch

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'bajienetwork/mobile'
          token: ${{ secrets.PAT }}
          submodules: recursive

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Set up NodeJS
        uses: actions/setup-node@v4.0.3
        with:
          cache: 'pnpm'

      - name: pnpm install
        run: pnpm install

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Grant execute permission for gradlew
        working-directory: android
        run: chmod +x gradlew

      - name: Build CMake
        working-directory: android
        run: ./gradlew buildCMakeDebug

      - name: Set up signing options
        working-directory: android
        env:
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
        run: |
          cat << EOF > ./signing.properties
          keystore.password=$SIGNING_STORE_PASSWORD
          key.alias=$SIGNING_KEY_ALIAS
          key.password=$SIGNING_KEY_PASSWORD
          EOF

      - name: Place release key
        working-directory: android
        run: echo ${{ secrets.RELEASE_KEY }} | base64 -d > release.keystore

      - name: Build meta-alpha release
        working-directory: android
        run: ./gradlew :app:assembleMeta-alphaRelease

      - name: Upload artifacts
        uses: actions/upload-artifact@v4.3.6
        with:
          name: android-latest
          path: ./android/app/build/outputs/apk/meta-alpha/release/*
        
