name: iOS CI

on: workflow_dispatch

jobs:
  build:

    runs-on: macos-latest

    steps:
      - name: Install the Apple certificate and provisioning profile
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
          PP_BASE64_1: ${{ secrets.PP_BASE64_1 }}
          PP_BASE64_2: ${{ secrets.PP_BASE64_2 }}
          PP_BASE64_3: ${{ secrets.PP_BASE64_3 }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          # create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
          PP_PATH="$HOME/Library/MobileDevice/Provisioning Profiles"
          
          # import certificate and provisioning profile from secrets
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH
          mkdir -p "$PP_PATH"
          for t in $(echo -n "$PP_BASE64_1" "$PP_BASE64_2" "$PP_BASE64_3")
          do
          echo $t | base64 -d > "$PP_PATH/$(echo $t | shasum | awk '{print $1}').mobileprovision"
          done
          
          # create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          
          # import certificate to keychain
          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

      - uses: actions/checkout@v4
        with:
          repository: 'bajienetwork/mobile'
          token: ${{ secrets.PAT }}
          submodules: recursive

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Set up NodeJS
        uses: actions/setup-node@v4.0.3
        with:
          cache: 'pnpm'

      - name: pnpm install
        run: pnpm install

      - name: Setup Cocoapods
        uses: maxim-lobanov/setup-cocoapods@v1.4.0
        with:
          version: '1.15.2'

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Set up Gomobile
        run: |
          go install golang.org/x/mobile/cmd/gomobile@latest
          gomobile init

      - name: Build BajieKit
        working-directory: ./ios/BajieKit
        run: make

      - name: Install Cocoapods
        working-directory: ./ios
        run: pod install

      - name: Build archive
        working-directory: ./ios
        run: |
          xcodebuild -workspace BajieNetwork.xcworkspace \
          -scheme "BajieNetwork" -archivePath $RUNNER_TEMP/bajie.xcarchive \
          -sdk iphoneos -configuration Release -destination generic/platform=iOS \
          archive

      - name: Upload artifacts
        uses: actions/upload-artifact@v4.3.6
        with:
          name: ios-latest
          path: ./${{ runner.temp }}/bajie.xcarchive
